# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://JoaoCampos89.github.io/
baseurl: /
title: João Campos	
author: Joao Campos
description: Personal blog and resume
avatar: profile.png
email: j.campos893@gmail.com
github: JoaoCampos89
# twitter: chrisstturner
# linkedin: username
# disqus: username
google_analytics: UA-69513336-1