# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://JoaoCampos89.github.io/
baseurl: /
title: João Campos
author: Joao Campos
description: Personal blog and resume
avatar: profile.png
email: j.campos893@gmail.com
github: JoaoCampos89
ufcgUrl: http://www.ufcg.edu.br/
unpUrl: https://unp.br/
linkedin: joaocampos89
vitae:
lattes: http://lattes.cnpq.br/9456252196930175
google_analytics: UA-69513336-1

collections:
  relayProtection:
    output: true
